#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    for i in range(W+2):
        print("#", end="")
    print()
    for i in range(H):
        print("#", end="")
        print(input(),end="")
        print("#")
    for i in range(W+2):
        print("#", end="")
    print()


    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
